version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    labels:
      - npm
      - dependencies
    groups:
      dependencies:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
    open-pull-requests-limit: 5
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
    labels:
      - bundler
      - dependencies
    groups:
      dependencies:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
    labels:
      - github-actions
      - dependencies
    groups:
      dependencies:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
    open-pull-requests-limit: 5
